### ISSUE TITLE
Error: &perlmmcc::mmc_get_isrc

### ISSUE THREAD

**Issue by whitepj** [rocky/Perl-Device-Cdio#5]
Hi Rocky,

I've been getting the following error:
Undefined subroutine &perlmmcc::mmc_get_isrc called at /usr/local/lib64/perl5/5.20.2/x86_64-linux-thread-multi/Device/Cdio/Track.pm line 303.

I first encountered this a while back -- and put it down to the fact that I was developing on a laptop without a real CDROM, using CDEmu instead. However, I now find that I am also getting the same error on a system with a standard SATA CDROM. Oddly, it doesn't occur every time, but does appear to depend upon the CD that I am trying to read at the time.

Can you suggest any reason why? Is this a bug, or my error?

Thanks 
Phil

[rip.pl.txt](https://github.com/rocky/Perl-Device-Cdio/files/1567992/rip.pl.txt)

**Comment by rocky** [comment]
Yes, there were definitely errors in `get_track_irsc()`.  Commit  46eb043 addresses them, **but**...

This code base is in the process of getting a face lift to support the current libcdio 1.1.0 API. No doubt you are using older versions of everything because CD-Text call in `rip.pl`  currently doesn't exist anymore and I haven't added something like that in yet back in.

So probably what you should do is take the diff from that commit and apply it to your source code. 

I think your rip.pl has a small bug in it: 

```
    $foo = $ctrack->get_track_isrc();
    $foo =~ s/-//g;		# because Device::Cdio gets it wrong, and inserts spacers.
    if ($foo){
```

should be:

```
    $foo = $ctrack->get_track_isrc();
    if ($foo){
        $foo =~ s/-//g;		# because Device::Cdio gets it wrong, and inserts spacers.
```

because you can't assume that `$foo` is defined or has a value set. 

Shame on you for noticing this a while back and not mentioning it. Yes, Device::Cdio will get things wrong sometimes. And it will stay that way unless people who use the library get a little more involved and mention the problem or even better fix it. 

I use the ratings of projects as an indication of whether to work on this project or others. The fact that no one other than myself means that I am not likely to bother with this project at all because no one cares about it. The only reason I happen to be modifying it is because the libcdio 1.1.0 API has changed. And even here, that was released a while back so I am now just getting around to fixing it after working on a number of other projects.

**Comment by whitepj** [comment]
Hi Rocky,

Thank you very much for the reply. I do apologise if it appeared that I was
complaining -- I really meant no such slight. You will have (no doubt)
noticed that my coding skills are exceptionally basic, and most of the bugs
I have to deal with are of my own making. After attempting several
incantations, I concluded that it was because I was using CDEmu to test
with. Oh, and I consider the hyphens within an ISRC to be a personal
preference that we disagree on, rather than 'wrong' per se. Sorry - perhaps
I should have edited out that line (which was there to remind me why I had
it in there originally, as the CD text was spitting out the condensed
version as expected, and I forget quickly).

As far as I know, Device::Cdio is the only module I have available that
allows me to interrogate the disk to retrieve the data I want without
performing a shell call. That makes it rather valuable to me. If I have the
ability, then I would offer a hand, but I'm not sure that would really help
you. Although I use Gentoo, which gives me reasonably current versions of
packages, I rarely go as far as patching and installing code from source.
I'll try, of course, but I am not really an expert here... (Test system is
Debian). Documentation, and testing, on the other hand, I can do if this is
helpful.

**Comment by rocky** [comment]
Sorry to be harsh. The documentation like everything else is lacking. So any suggestion you can make there would be most welcome. Thanks.
